import { useCallback, useEffect, useState } from "react";
import { ScrollView, View, Text, Pressable, StyleSheet, Alert } from "react-native";
import { useSession } from "../../src/session";
import { api } from "../../src/api";
import { colors, spacing } from "../../src/theme";

export default function ArtistApplications() {
  const { token, user } = useSession();
  const [items, setItems] = useState<any[]>([]); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { if (!token) return; try { setItems(await api<any[]>("/admin/artist-applications", {}, token)); } catch (e:any) { Alert.alert("Unable to load", e?.message || "Admin access required."); } }, [token]);
  useEffect(() => { load(); }, [load]);
  const review = async (id:string, approved:boolean) => { if (!token) return; setBusy(id); try { await api(`/admin/artist-applications/${id}/review`, { method:"POST", body:JSON.stringify({ approved, admin_note: approved ? "Approved" : "Please update your profile and resubmit." }) }, token); await load(); Alert.alert(approved ? "Approved" : "Rejected", approved ? "The artist is now public." : "The application was rejected."); } catch(e:any) { Alert.alert("Review failed", e?.message || "Try again."); } finally { setBusy(""); } };
  if (!user?.is_admin) return <View style={styles.center}><Text style={styles.title}>ADMIN ONLY</Text></View>;
  return <ScrollView style={styles.root} contentContainerStyle={styles.content}><Text style={styles.title}>ARTIST APPLICATIONS</Text><Text style={styles.subtitle}>VERIFY NEW ARTISTS</Text>{items.length===0 ? <Text style={styles.muted}>No applications yet.</Text> : items.map((a) => <View key={a.id} style={styles.card}><View style={styles.row}><Text style={styles.name}>{a.name}</Text><Text style={[styles.badge, a.status === "approved" ? styles.ok : a.status === "rejected" ? styles.no : styles.wait]}>{String(a.status).toUpperCase()}</Text></View><Text style={styles.detail}>{a.handle} • {a.city}</Text><Text style={styles.detail}>{a.studio}</Text><Text style={styles.detail}>₱{Number(a.rate_per_hour || 0).toLocaleString()}/HR</Text><Text style={styles.bio}>{a.bio}</Text>{a.phone ? <Text style={styles.detail}>PHONE: {a.phone}</Text> : null}{a.service_area ? <Text style={styles.detail}>SERVICE AREA: {a.service_area}</Text> : null}{a.status === "pending" ? <View style={styles.actions}><Pressable disabled={busy===a.id} onPress={()=>review(a.id,true)} style={styles.approve}><Text style={styles.actionText}>{busy===a.id ? "..." : "APPROVE"}</Text></Pressable><Pressable disabled={busy===a.id} onPress={()=>review(a.id,false)} style={styles.reject}><Text style={styles.actionText}>REJECT</Text></Pressable></View> : null}</View>)}</ScrollView>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.surface},content:{padding:spacing.lg,gap:spacing.md},center:{flex:1,backgroundColor:colors.surface,alignItems:"center",justifyContent:"center"},title:{color:colors.onSurface,fontSize:34,fontWeight:"900",letterSpacing:2},subtitle:{color:colors.brand,fontSize:11,fontWeight:"800",letterSpacing:2,marginBottom:spacing.md},muted:{color:colors.muted,fontSize:15},card:{backgroundColor:colors.surfaceSecondary,borderWidth:2,borderColor:colors.border,padding:spacing.md,gap:8},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:8},name:{color:colors.onSurface,fontSize:20,fontWeight:"900"},detail:{color:colors.muted,fontSize:13},bio:{color:colors.onSurface,fontSize:14,lineHeight:20,marginVertical:6},badge:{fontSize:9,fontWeight:"900",letterSpacing:1,padding:6,borderWidth:1},wait:{color:colors.brand,borderColor:colors.brand},ok:{color:colors.onSurface,borderColor:colors.borderStrong},no:{color:colors.error,borderColor:colors.error},actions:{flexDirection:"row",gap:10,marginTop:8},approve:{flex:1,backgroundColor:colors.brand,padding:14,alignItems:"center"},reject:{flex:1,borderWidth:2,borderColor:colors.error,padding:12,alignItems:"center"},actionText:{color:colors.onBrand,fontWeight:"900",letterSpacing:1.5}});
