import { useCallback, useEffect, useState } from "react";
import { ScrollView, View, Text, Pressable, StyleSheet, TextInput } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useSession } from "../../../src/session";
import { api } from "../../../src/api";
import { colors, spacing } from "../../../src/theme";

const php=(n:number)=>`₱${Number(n||0).toLocaleString("en-PH",{maximumFractionDigits:0})}`;
export default function ArtistSection(){
 const {section}=useLocalSearchParams<{section:string}>(); const router=useRouter(); const {token}=useSession();
 const [data,setData]=useState<any>(null); const [busy,setBusy]=useState(false); const [date,setDate]=useState(""); const [error,setError]=useState("");
 const load=useCallback(async()=>{if(!token)return;try{if(section==="bookings")setData(await api<any[]>("/artist/bookings",{},token));else if(section==="earnings")setData(await api<any>("/artist/earnings",{},token));else if(section==="availability")setData(await api<any>("/artist/me",{},token));else if(section==="profile")setData((await api<any>("/artist/me",{},token)).artist);else setData([]);}catch(e:any){setError(e?.message||"Could not load.")}},[token,section]);
 useEffect(()=>{load()},[load]);
 const save=async()=>{if(!token||!data?.artist||!/^\\d{4}-\\d{2}-\\d{2}$/.test(date))return;setBusy(true);try{const blocked=[...(data.artist.blocked_dates||[])];if(!blocked.includes(date))blocked.push(date);await api("/artist/availability",{method:"PATCH",body:JSON.stringify({blocked_dates:blocked})},token);setData({...data,artist:{...data.artist,blocked_dates:blocked.sort()}});setDate("")}catch(e:any){setError(e?.message||"Could not save.")}finally{setBusy(false)}};
 const remove=async(d:string)=>{if(!token||!data?.artist)return;setBusy(true);try{const blocked=(data.artist.blocked_dates||[]).filter((x:string)=>x!==d);await api("/artist/availability",{method:"PATCH",body:JSON.stringify({blocked_dates:blocked})},token);setData({...data,artist:{...data.artist,blocked_dates:blocked}})}catch(e:any){setError(e?.message||"Could not update.")}finally{setBusy(false)}};
 const title=(section||"").replace(/^./,x=>x.toUpperCase());
 return <ScrollView style={s.root} contentContainerStyle={s.content}><Pressable onPress={()=>router.replace("/artist/portal")}><Text style={s.back}>← ARTIST PORTAL</Text></Pressable><Text style={s.kicker}>TINTA ARTIST</Text><Text style={s.title}>{title.toUpperCase()}</Text>{error?<View style={s.error}><Text style={s.text}>{error}</Text></View>:null}
 {section==="bookings"&&Array.isArray(data)?<>{data.length?data.map((b:any)=><View style={s.card} key={b.id}><View style={s.row}><Text style={s.cardTitle}>{b.date} · {b.time_slot}</Text><Text style={s.badge}>{String(b.status).toUpperCase()}</Text></View><Text style={s.name}>{b.customer_name}</Text><Text style={s.text}>{b.description}</Text><Text style={s.meta}>{b.estimated_hours} HR · PAYMENT {String(b.payment_status).toUpperCase()}</Text></View>):<Empty text="NO BOOKINGS YET"/>}</>:null}
 {section==="earnings"&&data?<><View style={s.stat}><Text style={s.small}>PENDING PAYOUT</Text><Text style={s.big}>{php(data.pending_earnings)}</Text></View><View style={s.stat}><Text style={s.small}>PAID OUT</Text><Text style={s.big}>{php(data.paid_out)}</Text></View><Text style={s.section}>EARNINGS HISTORY</Text>{(data.entries||[]).map((r:any)=><View style={s.card} key={r.id||r.booking_id}><Text style={s.cardTitle}>{php(r.artist_earnings||r.amount)} · {String(r.status).replace("_"," ").toUpperCase()}</Text><Text style={s.meta}>{r.created_at?new Date(r.created_at).toLocaleDateString():""}</Text></View>)}</>:null}
 {section==="availability"&&data?.artist?<><View style={s.card}><Text style={s.cardTitle}>BLOCK A DATE</Text><Text style={s.text}>Use YYYY-MM-DD to mark yourself unavailable.</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.muted} style={s.input}/><Pressable disabled={busy} style={s.cta} onPress={save}><Text style={s.ctaText}>{busy?"SAVING...":"BLOCK DATE"}</Text></Pressable></View><Text style={s.section}>BLOCKED DATES</Text>{(data.artist.blocked_dates||[]).length?(data.artist.blocked_dates||[]).map((d:string)=><View style={s.dateRow} key={d}><Text style={s.cardTitle}>{d}</Text><Pressable onPress={()=>remove(d)}><Text style={s.remove}>REMOVE</Text></Pressable></View>):<Empty text="NO BLOCKED DATES"/>}</>:null}
 {section==="profile"&&data?<View style={s.card}><Text style={s.cardTitle}>{data.name}</Text><Text style={s.text}>@{data.handle}</Text><Text style={s.text}>{data.city} · {data.studio}</Text><Text style={s.text}>{php(data.rate_per_hour)}/HR</Text><Text style={s.text}>★ {data.rating||0} · {data.reviews_count||0} REVIEWS</Text><Text style={s.section}>BIO</Text><Text style={s.text}>{data.bio}</Text></View>:null}
 {section==="messages"?<Empty text="MESSAGING SECTION — CUSTOMER THREAD SUPPORT IS ALREADY IN TINTA AND WILL BE CONNECTED HERE NEXT."/>:null}</ScrollView>;
}
function Empty({text}:{text:string}){return <View style={s.empty}><Text style={s.text}>{text}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.surface},content:{padding:spacing.lg,gap:spacing.md,maxWidth:1000,width:"100%",alignSelf:"center",paddingBottom:60},back:{color:colors.brand,fontWeight:"900",letterSpacing:1.5},kicker:{color:colors.brand,fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:10},title:{color:colors.onSurface,fontSize:34,fontWeight:"900",letterSpacing:2},card:{borderWidth:2,borderColor:colors.border,padding:18,gap:7},row:{flexDirection:"row",justifyContent:"space-between",gap:10},cardTitle:{color:colors.onSurface,fontWeight:"900",fontSize:15},name:{color:colors.onSurface,fontSize:19,fontWeight:"900"},text:{color:colors.muted,fontSize:13,lineHeight:20},meta:{color:colors.muted,fontSize:10,fontWeight:"800",letterSpacing:1},badge:{color:colors.brand,fontSize:9,fontWeight:"900"},stat:{borderWidth:2,borderColor:colors.borderStrong,padding:20},small:{color:colors.muted,fontSize:9,fontWeight:"900",letterSpacing:1.5},big:{color:colors.onSurface,fontSize:30,fontWeight:"900",marginTop:5},section:{color:colors.brand,fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:spacing.md},input:{backgroundColor:colors.surfaceSecondary,borderWidth:2,borderColor:colors.border,color:colors.onSurface,padding:14,fontSize:15},cta:{backgroundColor:colors.brand,padding:16,alignItems:"center",marginTop:5},ctaText:{color:colors.onBrand,fontWeight:"900",letterSpacing:2},dateRow:{borderWidth:2,borderColor:colors.border,padding:16,flexDirection:"row",justifyContent:"space-between"},remove:{color:colors.brand,fontWeight:"900",fontSize:10,letterSpacing:1},empty:{borderWidth:2,borderColor:colors.border,padding:30,alignItems:"center"},error:{borderWidth:2,borderColor:colors.brand,padding:14}});
