import { useCallback, useEffect, useState } from "react";
import { ScrollView, View, Text, Pressable, StyleSheet, TextInput } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useSession } from "../../../src/session";
import { api } from "../../../src/api";
import { colors, spacing } from "../../../src/theme";

const php=(n:number)=>`₱${Number(n||0).toLocaleString("en-PH",{maximumFractionDigits:0})}`;
export default function ArtistSection(){
 const {section}=useLocalSearchParams<{section:string}>(); const router=useRouter(); const {token}=useSession();
 const [data,setData]=useState<any>(null); const [busy,setBusy]=useState(false); const [date,setDate]=useState(""); const [error,setError]=useState(""); const [editing,setEditing]=useState(false);
 const [name,setName]=useState(""); const [handle,setHandle]=useState(""); const [city,setCity]=useState(""); const [studio,setStudio]=useState("");
 const [stylesText,setStylesText]=useState(""); const [bio,setBio]=useState(""); const [rate,setRate]=useState(""); const [phone,setPhone]=useState(""); const [serviceArea,setServiceArea]=useState("");
 const [avatar,setAvatar]=useState(""); const [hero,setHero]=useState(""); const [portfolio,setPortfolio]=useState("");
 const fillProfile=(artist:any)=>{setName(artist?.name||"");setHandle(artist?.handle||"");setCity(artist?.city||"");setStudio(artist?.studio||"");setStylesText((artist?.styles||[]).join(", "));setBio(artist?.bio||"");setRate(artist?.rate_per_hour!=null?String(artist.rate_per_hour):"");setPhone(artist?.phone||"");setServiceArea(artist?.service_area||"");setAvatar(artist?.avatar||"");setHero(artist?.hero||"");setPortfolio((artist?.portfolio||[]).join(", "));};
 const load=useCallback(async()=>{if(!token)return;try{setError("");if(section==="bookings")setData(await api<any[]>("/artist/bookings",{},token));else if(section==="earnings")setData(await api<any>("/artist/earnings",{},token));else if(section==="availability")setData(await api<any>("/artist/me",{},token));else if(section==="profile"){const r=await api<any>("/artist/me",{},token);setData(r.artist);fillProfile(r.artist);}else setData([]);}catch(e:any){setError(e?.message||"Could not load.")}},[token,section]);
 useEffect(()=>{load()},[load]);
 const save=async()=>{setError("");if(!token||!data?.artist)return;if(!/^\d{4}-\d{2}-\d{2}$/.test(date)){setError("Use date format YYYY-MM-DD.");return;}setBusy(true);try{const blocked=[...(data.artist.blocked_dates||[])];if(!blocked.includes(date))blocked.push(date);await api("/artist/availability",{method:"PATCH",body:JSON.stringify({blocked_dates:blocked})},token);setData({...data,artist:{...data.artist,blocked_dates:blocked.sort()}});setDate("")}catch(e:any){setError(e?.message||"Could not save.")}finally{setBusy(false)}};
 const remove=async(d:string)=>{if(!token||!data?.artist)return;setError("");setBusy(true);try{const blocked=(data.artist.blocked_dates||[]).filter((x:string)=>x!==d);await api("/artist/availability",{method:"PATCH",body:JSON.stringify({blocked_dates:blocked})},token);setData({...data,artist:{...data.artist,blocked_dates:blocked}})}catch(e:any){setError(e?.message||"Could not update.")}finally{setBusy(false)}};
 const saveProfile=async()=>{setError("");if(!token)return;if(!name.trim()||!handle.trim()||!city.trim()||!studio.trim()){setError("Name, handle, city, and studio are required.");return;}if(bio.trim().length<10){setError("Bio must be at least 10 characters.");return;}const rateNumber=Number(rate);if(!Number.isFinite(rateNumber)||rateNumber<0){setError("Enter a valid rate per hour.");return;}setBusy(true);try{const updated=await api<any>("/artist/profile",{method:"PATCH",body:JSON.stringify({name:name.trim(),handle:handle.trim().replace(/^@/,""),city:city.trim(),studio:studio.trim(),styles:stylesText.split(",").map(x=>x.trim()).filter(Boolean),bio:bio.trim(),rate_per_hour:Math.round(rateNumber),phone:phone.trim(),service_area:serviceArea.trim(),avatar:avatar.trim(),hero:hero.trim(),portfolio:portfolio.split(",").map(x=>x.trim()).filter(Boolean)})},token);setData(updated);fillProfile(updated);setEditing(false)}catch(e:any){setError(e?.message||"Could not save profile.")}finally{setBusy(false)}};
 const title=(section||"").replace(/^./,x=>x.toUpperCase());
 return <ScrollView style={s.root} contentContainerStyle={s.content}><Pressable onPress={()=>router.replace("/artist/portal")}><Text style={s.back}>← ARTIST PORTAL</Text></Pressable><Text style={s.kicker}>TINTA ARTIST</Text><Text style={s.title}>{title.toUpperCase()}</Text>{error?<View style={s.error}><Text style={s.text}>{error}</Text></View>:null}
 {section==="bookings"&&Array.isArray(data)?<>{data.length?data.map((b:any)=><View style={s.card} key={b.id}><View style={s.row}><Text style={s.cardTitle}>{b.date} · {b.time_slot}</Text><Text style={s.badge}>{String(b.status).toUpperCase()}</Text></View><Text style={s.name}>{b.customer_name}</Text><Text style={s.text}>{b.description}</Text><Text style={s.meta}>{b.estimated_hours} HR · PAYMENT {String(b.payment_status).toUpperCase()}</Text></View>):<Empty text="NO BOOKINGS YET"/>}</>:null}
 {section==="earnings"&&data?<><View style={s.stat}><Text style={s.small}>PENDING PAYOUT</Text><Text style={s.big}>{php(data.pending_earnings)}</Text></View><View style={s.stat}><Text style={s.small}>PAID OUT</Text><Text style={s.big}>{php(data.paid_out)}</Text></View><Text style={s.section}>EARNINGS HISTORY</Text>{(data.entries||[]).map((r:any)=><View style={s.card} key={r.id||r.booking_id}><Text style={s.cardTitle}>{php(r.artist_earnings||r.amount)} · {String(r.status).replace("_"," ").toUpperCase()}</Text><Text style={s.meta}>{r.created_at?new Date(r.created_at).toLocaleDateString():""}</Text></View>)}</>:null}
 {section==="availability"&&data?.artist?<><View style={s.card}><Text style={s.cardTitle}>BLOCK A DATE</Text><Text style={s.text}>Use YYYY-MM-DD to mark yourself unavailable.</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.muted} style={s.input}/><Pressable disabled={busy} style={s.cta} onPress={save}><Text style={s.ctaText}>{busy?"SAVING...":"BLOCK DATE"}</Text></Pressable></View><Text style={s.section}>BLOCKED DATES</Text>{(data.artist.blocked_dates||[]).length?(data.artist.blocked_dates||[]).map((d:string)=><View style={s.dateRow} key={d}><Text style={s.cardTitle}>{d}</Text><Pressable disabled={busy} onPress={()=>remove(d)}><Text style={s.remove}>REMOVE</Text></Pressable></View>):<Empty text="NO BLOCKED DATES"/>}</>:null}
 {section==="profile"&&data?(editing?<View style={s.card}><Text style={s.cardTitle}>EDIT ARTIST PROFILE</Text>{[["NAME",name,setName],["HANDLE",handle,setHandle],["CITY",city,setCity],["STUDIO",studio,setStudio],["STYLES (COMMA SEPARATED)",stylesText,setStylesText],["BIO",bio,setBio],["RATE PER HOUR (PHP)",rate,setRate],["PHONE",phone,setPhone],["SERVICE AREA",serviceArea,setServiceArea],["AVATAR URL",avatar,setAvatar],["HERO IMAGE URL",hero,setHero],["PORTFOLIO URLS (COMMA SEPARATED)",portfolio,setPortfolio]].map(([label,value,setter]:any)=><View key={label}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={setter} multiline={label==="BIO"} keyboardType={label.includes("RATE")?"numeric":"default"} placeholder={label} placeholderTextColor={colors.muted} style={[s.input,label==="BIO"&&s.bio]}/></View>)}<Pressable disabled={busy} style={[s.cta,busy&&{opacity:.5}]} onPress={saveProfile}><Text style={s.ctaText}>{busy?"SAVING...":"SAVE PROFILE"}</Text></Pressable><Pressable disabled={busy} style={s.secondary} onPress={()=>{setEditing(false);fillProfile(data)}}><Text style={s.secondaryText}>CANCEL</Text></Pressable></View>:<View style={s.card}><View style={s.row}><Text style={s.cardTitle}>{data.name}</Text><Pressable onPress={()=>setEditing(true)}><Text style={s.remove}>EDIT</Text></Pressable></View><Text style={s.text}>@{data.handle}</Text><Text style={s.text}>{data.city} · {data.studio}</Text><Text style={s.text}>{php(data.rate_per_hour)}/HR</Text><Text style={s.text}>★ {data.rating||0} · {data.reviews_count||0} REVIEWS</Text>{(data.styles||[]).length?<><Text style={s.section}>STYLES</Text><Text style={s.text}>{data.styles.join(" · ")}</Text></>:null}<Text style={s.section}>BIO</Text><Text style={s.text}>{data.bio}</Text>{data.service_area?<Text style={s.text}>SERVICE AREA · {data.service_area}</Text>:null}{data.phone?<Text style={s.text}>PHONE · {data.phone}</Text>:null}</View>):null}
 {section==="messages"?<Empty text="MESSAGING SECTION — CUSTOMER THREAD SUPPORT IS ALREADY IN TINTA AND WILL BE CONNECTED HERE NEXT."/>:null}</ScrollView>;
}
function Empty({text}:{text:string}){return <View style={s.empty}><Text style={s.text}>{text}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.surface},content:{padding:spacing.lg,gap:spacing.md,maxWidth:1000,width:"100%",alignSelf:"center",paddingBottom:60},back:{color:colors.brand,fontWeight:"900",letterSpacing:1.5},kicker:{color:colors.brand,fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:10},title:{color:colors.onSurface,fontSize:34,fontWeight:"900",letterSpacing:2},card:{borderWidth:2,borderColor:colors.border,padding:18,gap:7},row:{flexDirection:"row",justifyContent:"space-between",gap:10},cardTitle:{color:colors.onSurface,fontWeight:"900",fontSize:15},name:{color:colors.onSurface,fontSize:19,fontWeight:"900"},text:{color:colors.muted,fontSize:13,lineHeight:20},meta:{color:colors.muted,fontSize:10,fontWeight:"800",letterSpacing:1},badge:{color:colors.brand,fontSize:9,fontWeight:"900"},stat:{borderWidth:2,borderColor:colors.borderStrong,padding:20},small:{color:colors.muted,fontSize:9,fontWeight:"900",letterSpacing:1.5},big:{color:colors.onSurface,fontSize:30,fontWeight:"900",marginTop:5},section:{color:colors.brand,fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:spacing.md},label:{color:colors.muted,fontSize:10,fontWeight:"800",letterSpacing:1.5,marginTop:spacing.sm},input:{backgroundColor:colors.surfaceSecondary,borderWidth:2,borderColor:colors.border,color:colors.onSurface,padding:14,fontSize:15},bio:{minHeight:110,textAlignVertical:"top"},cta:{backgroundColor:colors.brand,padding:16,alignItems:"center",marginTop:5},ctaText:{color:colors.onBrand,fontWeight:"900",letterSpacing:2},secondary:{borderWidth:2,borderColor:colors.borderStrong,padding:15,alignItems:"center",marginTop:8},secondaryText:{color:colors.onSurface,fontWeight:"800",letterSpacing:2,textAlign:"center"},dateRow:{borderWidth:2,borderColor:colors.border,padding:16,flexDirection:"row",justifyContent:"space-between"},remove:{color:colors.brand,fontWeight:"900",fontSize:10,letterSpacing:1},empty:{borderWidth:2,borderColor:colors.border,padding:30,alignItems:"center"},error:{borderWidth:2,borderColor:colors.brand,padding:14}});
