import { useCallback, useEffect, useState } from "react";
import { View, Text, StyleSheet, FlatList, Pressable, ActivityIndicator, RefreshControl } from "react-native";
import { useRouter } from "expo-router";
import { useSession } from "../../src/session";
import { api } from "../../src/api";
import { colors, spacing } from "../../src/theme";

type Contact={id:string;name:string;role:string;avatar?:string;conversation_id:string};
export default function ArtistMessages(){const router=useRouter();const{token}=useSession();const[items,setItems]=useState<Contact[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{if(!token)return;try{const contacts=await api<Contact[]>("/chat/contacts",{},token);setItems(contacts.filter(x=>x.role==="customer"))}catch{setItems([])}finally{setLoading(false);setRefreshing(false)}},[token]);useEffect(()=>{load()},[load]);return <View style={s.root}><View style={s.header}><Pressable onPress={()=>router.replace("/artist/portal")}><Text style={s.back}>← ARTIST PORTAL</Text></Pressable><Text style={s.kicker}>TINTA ARTIST</Text><Text style={s.title}>MESSAGES</Text></View>{loading?<View style={s.center}><ActivityIndicator color={colors.brand}/></View>:<FlatList data={items} keyExtractor={x=>x.conversation_id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}} tintColor={colors.brand}/>} renderItem={({item})=><Pressable style={s.row} onPress={()=>router.push(`/chat/conversation/${encodeURIComponent(item.conversation_id)}`)}><View style={s.avatar}><Text style={s.avatarText}>{item.name.slice(0,1).toUpperCase()}</Text></View><View style={s.body}><Text style={s.name}>{item.name.toUpperCase()}</Text><Text style={s.sub}>DIRECT MESSAGE · CUSTOMER</Text></View><Text style={s.arrow}>›</Text></Pressable>}/>}</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.surface},header:{padding:spacing.lg,borderBottomWidth:2,borderBottomColor:colors.borderStrong},back:{color:colors.brand,fontWeight:"900",letterSpacing:1.5},kicker:{color:colors.brand,fontSize:10,fontWeight:"900",letterSpacing:2,marginTop:12},title:{color:colors.onSurface,fontSize:34,fontWeight:"900",letterSpacing:2},center:{flex:1,alignItems:"center",justifyContent:"center"},row:{flexDirection:"row",alignItems:"center",gap:spacing.md,padding:spacing.lg,borderBottomWidth:1,borderBottomColor:colors.divider},avatar:{width:52,height:52,borderWidth:2,borderColor:colors.brand,alignItems:"center",justifyContent:"center",backgroundColor:colors.surfaceSecondary},avatarText:{color:colors.brand,fontWeight:"900",fontSize:17},body:{flex:1},name:{color:colors.onSurface,fontWeight:"900",fontSize:14,letterSpacing:1},sub:{color:colors.muted,fontSize:10,fontWeight:"800",letterSpacing:1.2,marginTop:4},arrow:{color:colors.brand,fontSize:28}});
