import { useCallback, useEffect, useRef, useState } from "react";
import { View, Text, StyleSheet, FlatList, Pressable, TextInput, KeyboardAvoidingView, Platform, ActivityIndicator } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import Icon from "@react-native-vector-icons/feather";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { api } from "../../../src/api";
import { useSession } from "../../../src/session";
import { colors, spacing } from "../../../src/theme";

type Msg={id:string;conversation_id:string;sender_id:string;sender_role:string;sender_name:string;text:string;created_at:string};

export default function UniversalChat(){
 const {conversationId}=useLocalSearchParams<{conversationId:string}>(); const router=useRouter(); const insets=useSafeAreaInsets(); const {token,user}=useSession();
 const [title,setTitle]=useState("CHAT"); const [role,setRole]=useState(""); const [msgs,setMsgs]=useState<Msg[]>([]); const [text,setText]=useState(""); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const list=useRef<FlatList<Msg>>(null);
 const load=useCallback(async()=>{if(!token||!conversationId)return;try{const r=await api<any>(`/chat/conversations/${encodeURIComponent(conversationId)}`,{},token);setTitle(r.title||"CHAT");setRole(r.role||"");setMsgs(r.messages||[]);}catch{}finally{setLoading(false)}},[token,conversationId]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{const id=setInterval(()=>load(),4000);return()=>clearInterval(id)},[load]);
 const send=async()=>{const t=text.trim();if(!t||sending||!token)return;setText("");setSending(true);try{await api("/chat/send",{method:"POST",body:JSON.stringify({conversation_id:conversationId,text:t,bot:conversationId?.startsWith("bot:")})},token);await load();setTimeout(()=>list.current?.scrollToEnd({animated:true}),80)}catch(e:any){setText(t)}finally{setSending(false)}};
 if(loading)return <View style={s.center}><ActivityIndicator color={colors.brand}/></View>;
 return <KeyboardAvoidingView style={s.root} behavior={Platform.OS==="ios"?"padding":undefined}>
  <View style={[s.header,{paddingTop:insets.top+spacing.sm}]}><Pressable onPress={()=>router.back()} style={s.icon}><Icon name="arrow-left" size={20} color={colors.onSurface}/></Pressable><View style={{flex:1}}><Text style={s.title}>{title.toUpperCase()}</Text><Text style={s.sub}>{role==="bot"?"TINTA AI ASSISTANT":"DIRECT MESSAGE"}</Text></View></View>
  <FlatList ref={list} data={msgs} keyExtractor={m=>m.id} contentContainerStyle={s.list} onContentSizeChange={()=>list.current?.scrollToEnd({animated:false})} renderItem={({item})=>{const mine=item.sender_id===user?.id;return <View style={[s.row,mine?s.mine:s.theirs]}><View style={[s.bubble,mine?s.mineBubble:s.theirBubble]}>{!mine&&<Text style={s.sender}>{item.sender_name}</Text>}<Text style={[s.msg,mine&&{color:colors.onBrand}]}>{item.text}</Text><Text style={[s.time,mine&&{color:colors.onBrand}]}>{new Date(item.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</Text></View></View>}} ListEmptyComponent={<View style={s.empty}><Text style={s.emptyTitle}>{role==="bot"?"TALK TO TINTA AI":"START THE CONVERSATION"}</Text><Text style={s.emptySub}>{role==="bot"?"Ask about bookings, artists, GCash or TINTA.":"SEND A MESSAGE"}</Text></View>}/>
  <View style={[s.bar,{paddingBottom:insets.bottom+spacing.sm}]}><TextInput value={text} onChangeText={setText} placeholder="TYPE MESSAGE..." placeholderTextColor={colors.muted} style={s.input} multiline maxLength={1000}/><Pressable onPress={send} disabled={!text.trim()||sending} style={[s.send,(!text.trim()||sending)&&{opacity:.45}]}><Icon name="send" size={20} color={colors.onBrand}/></Pressable></View>
 </KeyboardAvoidingView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.surface},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:colors.surface},header:{flexDirection:"row",alignItems:"center",gap:spacing.md,paddingHorizontal:spacing.md,paddingBottom:spacing.md,borderBottomWidth:2,borderBottomColor:colors.borderStrong},icon:{width:40,height:40,borderWidth:2,borderColor:colors.borderStrong,alignItems:"center",justifyContent:"center"},title:{color:colors.onSurface,fontSize:16,fontWeight:"900",letterSpacing:1.5},sub:{color:colors.brand,fontSize:10,fontWeight:"800",letterSpacing:1.5,marginTop:3},list:{padding:spacing.lg,gap:spacing.sm,paddingBottom:spacing.xl},row:{flexDirection:"row"},mine:{justifyContent:"flex-end"},theirs:{justifyContent:"flex-start"},bubble:{maxWidth:"82%",paddingHorizontal:spacing.md,paddingVertical:spacing.sm,borderWidth:2},mineBubble:{backgroundColor:colors.brand,borderColor:colors.brand},theirBubble:{backgroundColor:colors.surfaceSecondary,borderColor:colors.border},sender:{color:colors.brand,fontSize:10,fontWeight:"900",letterSpacing:1,marginBottom:3},msg:{color:colors.onSurface,fontSize:14,lineHeight:20},time:{color:colors.muted,fontSize:9,marginTop:4},bar:{flexDirection:"row",alignItems:"flex-end",gap:spacing.sm,padding:spacing.sm,borderTopWidth:2,borderTopColor:colors.borderStrong},input:{flex:1,minHeight:44,maxHeight:120,backgroundColor:colors.surfaceSecondary,borderWidth:2,borderColor:colors.border,color:colors.onSurface,paddingHorizontal:spacing.md,paddingVertical:spacing.sm,fontSize:14},send:{width:44,height:44,backgroundColor:colors.brand,alignItems:"center",justifyContent:"center"},empty:{padding:spacing.xl,alignItems:"center"},emptyTitle:{color:colors.onSurface,fontSize:20,fontWeight:"900",letterSpacing:2,textAlign:"center"},emptySub:{color:colors.muted,fontSize:11,fontWeight:"800",letterSpacing:1.5,marginTop:5}});
